name: Auto Publish Metadata

on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Deps
        run: pip install pyyaml jinja2
      - name: Generate Metadata
        run: python generate_meta/main.py --config config.yaml

  push-readme:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v3
      - name: Commit README if changed
        run: |
          git config --global user.name 'autobot'
          git config --global user.email 'bot@stratumresearch.org'
          git add README.md
          git diff --quiet || git commit -m 'auto-update README' && git push
